// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// vectorized_pdist
NumericMatrix vectorized_pdist(NumericMatrix Ar, NumericMatrix Br);
RcppExport SEXP geomod3D_vectorized_pdist(SEXP ArSEXP, SEXP BrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Ar(ArSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Br(BrSEXP);
    rcpp_result_gen = Rcpp::wrap(vectorized_pdist(Ar, Br));
    return rcpp_result_gen;
END_RCPP
}
// covd1_gaussian
NumericMatrix covd1_gaussian(NumericMatrix u, NumericMatrix v, NumericMatrix dir1, NumericMatrix A);
RcppExport SEXP geomod3D_covd1_gaussian(SEXP uSEXP, SEXP vSEXP, SEXP dir1SEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dir1(dir1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(covd1_gaussian(u, v, dir1, A));
    return rcpp_result_gen;
END_RCPP
}
// covd2_gaussian
NumericMatrix covd2_gaussian(NumericMatrix u, NumericMatrix v, NumericMatrix dir1, NumericMatrix dir2, NumericMatrix A);
RcppExport SEXP geomod3D_covd2_gaussian(SEXP uSEXP, SEXP vSEXP, SEXP dir1SEXP, SEXP dir2SEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dir1(dir1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dir2(dir2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(covd2_gaussian(u, v, dir1, dir2, A));
    return rcpp_result_gen;
END_RCPP
}
// covd1_cubic
NumericMatrix covd1_cubic(NumericMatrix u, NumericMatrix v, NumericMatrix dir1, NumericMatrix A);
RcppExport SEXP geomod3D_covd1_cubic(SEXP uSEXP, SEXP vSEXP, SEXP dir1SEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dir1(dir1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(covd1_cubic(u, v, dir1, A));
    return rcpp_result_gen;
END_RCPP
}
// covd2_cubic
NumericMatrix covd2_cubic(NumericMatrix u, NumericMatrix v, NumericMatrix dir1, NumericMatrix dir2, NumericMatrix A);
RcppExport SEXP geomod3D_covd2_cubic(SEXP uSEXP, SEXP vSEXP, SEXP dir1SEXP, SEXP dir2SEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dir1(dir1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dir2(dir2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(covd2_cubic(u, v, dir1, dir2, A));
    return rcpp_result_gen;
END_RCPP
}
// covd1_matern1
NumericMatrix covd1_matern1(NumericMatrix u, NumericMatrix v, NumericMatrix dir1, NumericMatrix A);
RcppExport SEXP geomod3D_covd1_matern1(SEXP uSEXP, SEXP vSEXP, SEXP dir1SEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dir1(dir1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(covd1_matern1(u, v, dir1, A));
    return rcpp_result_gen;
END_RCPP
}
// covd2_matern1
NumericMatrix covd2_matern1(NumericMatrix u, NumericMatrix v, NumericMatrix dir1, NumericMatrix dir2, NumericMatrix A);
RcppExport SEXP geomod3D_covd2_matern1(SEXP uSEXP, SEXP vSEXP, SEXP dir1SEXP, SEXP dir2SEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dir1(dir1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dir2(dir2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(covd2_matern1(u, v, dir1, dir2, A));
    return rcpp_result_gen;
END_RCPP
}
// covd1_matern2
NumericMatrix covd1_matern2(NumericMatrix u, NumericMatrix v, NumericMatrix dir1, NumericMatrix A);
RcppExport SEXP geomod3D_covd1_matern2(SEXP uSEXP, SEXP vSEXP, SEXP dir1SEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dir1(dir1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(covd1_matern2(u, v, dir1, A));
    return rcpp_result_gen;
END_RCPP
}
// covd2_matern2
NumericMatrix covd2_matern2(NumericMatrix u, NumericMatrix v, NumericMatrix dir1, NumericMatrix dir2, NumericMatrix A);
RcppExport SEXP geomod3D_covd2_matern2(SEXP uSEXP, SEXP vSEXP, SEXP dir1SEXP, SEXP dir2SEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dir1(dir1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dir2(dir2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(covd2_matern2(u, v, dir1, dir2, A));
    return rcpp_result_gen;
END_RCPP
}
// covd1_cauchy
NumericMatrix covd1_cauchy(NumericMatrix u, NumericMatrix v, NumericMatrix dir1, NumericMatrix A, double p);
RcppExport SEXP geomod3D_covd1_cauchy(SEXP uSEXP, SEXP vSEXP, SEXP dir1SEXP, SEXP ASEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dir1(dir1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(covd1_cauchy(u, v, dir1, A, p));
    return rcpp_result_gen;
END_RCPP
}
// covd2_cauchy
NumericMatrix covd2_cauchy(NumericMatrix u, NumericMatrix v, NumericMatrix dir1, NumericMatrix dir2, NumericMatrix A, double p);
RcppExport SEXP geomod3D_covd2_cauchy(SEXP uSEXP, SEXP vSEXP, SEXP dir1SEXP, SEXP dir2SEXP, SEXP ASEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dir1(dir1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dir2(dir2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(covd2_cauchy(u, v, dir1, dir2, A, p));
    return rcpp_result_gen;
END_RCPP
}
